/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as icsrSol from "./ICSR.sol";
export type { icsrSol };
import type * as mockDexSol from "./MockDEX.sol";
export type { mockDexSol };
export type { Turnstile } from "./Turnstile";
export type { TurnstileBond } from "./TurnstileBond";
