/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Signer,
  utils,
  Contract,
  ContractFactory,
  BigNumberish,
  Overrides,
} from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  TurnstileUser,
  TurnstileUserInterface,
} from "../../../contracts/ICSR.sol/TurnstileUser";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_turnstile",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_id",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "turnstile",
    outputs: [
      {
        internalType: "contract ITurnstile",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60a060405234801561001057600080fd5b506040516101c33803806101c383398101604081905261002f916100a6565b6001600160a01b0382166080819052604051630981022760e31b815260048101839052634c081138906024016020604051808303816000875af115801561007a573d6000803e3d6000fd5b505050506040513d601f19601f8201168201806040525081019061009e91906100e0565b5050506100f9565b600080604083850312156100b957600080fd5b82516001600160a01b03811681146100d057600080fd5b6020939093015192949293505050565b6000602082840312156100f257600080fd5b5051919050565b60805160b261011160003960006031015260b26000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063b38d435714602d575b600080fd5b60537f000000000000000000000000000000000000000000000000000000000000000081565b60405173ffffffffffffffffffffffffffffffffffffffff909116815260200160405180910390f3fea26469706673582212207c04f33918e6bd510b5563f4f5095466341b4898265ab78aba703cc26b706c2c64736f6c63430008120033";

type TurnstileUserConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: TurnstileUserConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class TurnstileUser__factory extends ContractFactory {
  constructor(...args: TurnstileUserConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    _turnstile: PromiseOrValue<string>,
    _id: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<TurnstileUser> {
    return super.deploy(
      _turnstile,
      _id,
      overrides || {}
    ) as Promise<TurnstileUser>;
  }
  override getDeployTransaction(
    _turnstile: PromiseOrValue<string>,
    _id: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(_turnstile, _id, overrides || {});
  }
  override attach(address: string): TurnstileUser {
    return super.attach(address) as TurnstileUser;
  }
  override connect(signer: Signer): TurnstileUser__factory {
    return super.connect(signer) as TurnstileUser__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): TurnstileUserInterface {
    return new utils.Interface(_abi) as TurnstileUserInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TurnstileUser {
    return new Contract(address, _abi, signerOrProvider) as TurnstileUser;
  }
}
