/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface MockDEXInterface extends utils.Interface {
  functions: {
    "tokenId()": FunctionFragment;
    "turnstile()": FunctionFragment;
    "turnstileBond()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "tokenId" | "turnstile" | "turnstileBond"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "tokenId", values?: undefined): string;
  encodeFunctionData(functionFragment: "turnstile", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "turnstileBond",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "tokenId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "turnstile", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "turnstileBond",
    data: BytesLike
  ): Result;

  events: {};
}

export interface MockDEX extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MockDEXInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    tokenId(overrides?: CallOverrides): Promise<[BigNumber]>;

    turnstile(overrides?: CallOverrides): Promise<[string]>;

    turnstileBond(overrides?: CallOverrides): Promise<[string]>;
  };

  tokenId(overrides?: CallOverrides): Promise<BigNumber>;

  turnstile(overrides?: CallOverrides): Promise<string>;

  turnstileBond(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    tokenId(overrides?: CallOverrides): Promise<BigNumber>;

    turnstile(overrides?: CallOverrides): Promise<string>;

    turnstileBond(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    tokenId(overrides?: CallOverrides): Promise<BigNumber>;

    turnstile(overrides?: CallOverrides): Promise<BigNumber>;

    turnstileBond(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    tokenId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    turnstile(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    turnstileBond(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
