/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ITurnstileBond,
  ITurnstileBondInterface,
} from "../../../contracts/MockDEX.sol/ITurnstileBond";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
    ],
    name: "cancel",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_minGoal",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_maxGoal",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_premium",
        type: "uint256",
      },
    ],
    name: "start",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ITurnstileBond__factory {
  static readonly abi = _abi;
  static createInterface(): ITurnstileBondInterface {
    return new utils.Interface(_abi) as ITurnstileBondInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITurnstileBond {
    return new Contract(address, _abi, signerOrProvider) as ITurnstileBond;
  }
}
